version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  tests:
    docker:
      - image: circleci/node:14.16.0-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version
      - node/install-packages:
        pkg-manager: npm
      - run: npm lint

workflows:
  ci:
    jobs:
      - tests
