version: 2.1

orbs:
  node: circleci/node@4.2.0
  codecov: codecov/codecov@1.1.3

jobs:
  tests:
    docker:
      - image: circleci/node:14.16.0-browsers
    steps:
      - checkout
      - node/install-npm
      - run:
          name: Show Node Version
          command: |
            node --version
            npm --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint check
          command: npm run lint
      - run:
          name: Run unit tests with covereage
          command: npm run cover
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: npx run chromatic --project-token=${CHROMATIC_TOKEN} --exit-zero-on-changes
  versioning:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version maurolsn web-mauro-leandro

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - chromatic-deployment
