version: 2.1

orbs:
  node: circleci/node@4.2.0
  codecov: codecov/codecov@1.1.3

jobs:
  tests:
    docker:
      - image: circleci/node:14.16.0-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version
      - node/install-packages:
          pkg-manager: npm
      - run: npm run lint
      - run: npm run cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version maurolsn web-mauro-leandro

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
