version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  setup:
    docker:
      - image: cicleci/node:14.16.0-browsers
    steps:
      - checkout
      - node/install-npm
      - run: node --version
      - run: npm --version

workflows:
  ci:
    jobs:
      - setup
